repos:

  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.8
        exclude: >
          (?x)^(
            scripts/gen-docs-index|
          )$
        args: ['--line-length', '120']

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
        exclude: devlocal-*
      - id: fix-encoding-pragma
      - id: trailing-whitespace

  - repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.25.0
    hooks:
      - id: markdownlint
        entry: markdownlint --ignore .github/*.md
