repos:

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.9
        exclude: ^openapi_client

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: ^openapi_client

  - repo: https://github.com/trussworks/pre-commit-hooks
    rev: v1.1.1
    hooks:
      - id: circleci-validate
      - id: markdown-toc
      - id: hadolint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
        exclude: devlocal-*
      - id: fix-encoding-pragma
        exclude: openapi_client
      - id: trailing-whitespace
        exclude: openapi_client

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
      - id: markdownlint
        entry: markdownlint --ignore .github/*.md --ignore openapi_client/**/*

  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
        args: [-x]
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pipenv run pyright
        language: system
        pass_filenames: false
        types: [python]
