version: '3.8'

services:
  prime:
    build: .
    ports:
     - "8089:8089"
    environment:
     - DEVLOCAL_AUTH=true
     - MOVE_MIL_EXP_TLS_CERT
     - MOVE_MIL_EXP_TLS_KEY
    command: -f /app/locustfiles/prime.py --host exp
