version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfiles/prime.py --master -H http://master:8089
    # docker run -p 8089:8089 -v $PWD:/mnt/locust locustio/locust -f /mnt/locust/locustfiles/prime.py
    # docker run -p 8089:8089 -v $PWD locustio/locust -f locustfiles/prime.py

  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfiles/prime.py --worker --master-host master