version: '3.8'

services:
  prime:
    build: .
    ports:
     - "8089:8089"
    environment:
     - DEVLOCAL_AUTH=true
    # - DEVLOCAL_CA=/config/tls/devlocal-ca.pem
     - MOVE_MIL_DOD_TLS_CERT
     - MOVE_MIL_DOD_TLS_KEY
    command: -f /app/locustfiles/prime.py --host exp
