"""
    move.mil API

    The API for move.mil  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: dp3@truss.works
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ghc_client
from ghc_client.model.move_status import MoveStatus


class TestMoveStatus(unittest.TestCase):
    """MoveStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMoveStatus(self):
        """Test MoveStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MoveStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
