"""
    move.mil API

    The API for move.mil  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: dp3@truss.works
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ghc_client
from ghc_client.model.shipment_payment_sit_balance import ShipmentPaymentSITBalance
globals()['ShipmentPaymentSITBalance'] = ShipmentPaymentSITBalance
from ghc_client.model.shipments_payment_sit_balance import ShipmentsPaymentSITBalance


class TestShipmentsPaymentSITBalance(unittest.TestCase):
    """ShipmentsPaymentSITBalance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testShipmentsPaymentSITBalance(self):
        """Test ShipmentsPaymentSITBalance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ShipmentsPaymentSITBalance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
