"""
    MilMove GHC API

    The GHC API is a RESTful API that enables the Office application for MilMove.  All endpoints are located under `/ghc/v1`.   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: milmove-developers@caci.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import ghc_client
from ghc_client.api.customer_support_remarks_api import CustomerSupportRemarksApi  # noqa: E501


class TestCustomerSupportRemarksApi(unittest.TestCase):
    """CustomerSupportRemarksApi unit test stubs"""

    def setUp(self):
        self.api = CustomerSupportRemarksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_customer_support_remark_for_move(self):
        """Test case for create_customer_support_remark_for_move

        Creates a customer support remark for a move  # noqa: E501
        """
        pass

    def test_delete_customer_support_remark(self):
        """Test case for delete_customer_support_remark

        Soft deletes a customer support remark by ID  # noqa: E501
        """
        pass

    def test_get_customer_support_remarks_for_move(self):
        """Test case for get_customer_support_remarks_for_move

        Fetches customer support remarks using the move code (locator).  # noqa: E501
        """
        pass

    def test_update_customer_support_remark_for_move(self):
        """Test case for update_customer_support_remark_for_move

        Updates a customer support remark for a move  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
