"""
    move.mil API

    The API for move.mil  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: dp3@truss.works
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ghc_client
from ghc_client.model.address import Address
from ghc_client.model.backup_contact import BackupContact
globals()['Address'] = Address
globals()['BackupContact'] = BackupContact
from ghc_client.model.update_customer_payload import UpdateCustomerPayload


class TestUpdateCustomerPayload(unittest.TestCase):
    """UpdateCustomerPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateCustomerPayload(self):
        """Test UpdateCustomerPayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateCustomerPayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
