"""
    MilMove GHC API

    The GHC API is a RESTful API that enables the Office application for MilMove.  All endpoints are located under `/ghc/v1`.   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: milmove-developers@caci.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import ghc_client
from ghc_client.api.ppm_api import PpmApi  # noqa: E501


class TestPpmApi(unittest.TestCase):
    """PpmApi unit test stubs"""

    def setUp(self):
        self.api = PpmApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_finish_document_review(self):
        """Test case for finish_document_review

        Updates a PPM shipment's status after document review  # noqa: E501
        """
        pass

    def test_get_ppm_actual_weight(self):
        """Test case for get_ppm_actual_weight

        Get the actual weight for a PPM shipment  # noqa: E501
        """
        pass

    def test_get_ppm_closeout(self):
        """Test case for get_ppm_closeout

        Get the closeout calcuations for the specified PPM shipment  # noqa: E501
        """
        pass

    def test_get_ppm_documents(self):
        """Test case for get_ppm_documents

        Gets all the PPM documents for a PPM shipment  # noqa: E501
        """
        pass

    def test_get_ppmsit_estimated_cost(self):
        """Test case for get_ppmsit_estimated_cost

        Get the SIT estimated cost for a PPM shipment  # noqa: E501
        """
        pass

    def test_show_aoa_packet(self):
        """Test case for show_aoa_packet

        Downloads AOA Packet form PPMShipment as a PDF  # noqa: E501
        """
        pass

    def test_show_payment_packet(self):
        """Test case for show_payment_packet

        Returns PPM payment packet  # noqa: E501
        """
        pass

    def test_update_moving_expense(self):
        """Test case for update_moving_expense

        Updates the moving expense  # noqa: E501
        """
        pass

    def test_update_ppmsit(self):
        """Test case for update_ppmsit

        Updates a PPM shipment's SIT values  # noqa: E501
        """
        pass

    def test_update_pro_gear_weight_ticket(self):
        """Test case for update_pro_gear_weight_ticket

        Updates a pro-gear weight ticket  # noqa: E501
        """
        pass

    def test_update_weight_ticket(self):
        """Test case for update_weight_ticket

        Updates a weight ticket document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
