"""
    MilMove GHC API

    The GHC API is a RESTful API that enables the Office application for MilMove.  All endpoints are located under `/ghc/v1`.   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: milmove-developers@caci.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ghc_client
from ghc_client.model.affiliation import Affiliation
from ghc_client.model.backup_contact import BackupContact
from ghc_client.model.update_customer_payload_current_address import UpdateCustomerPayloadCurrentAddress
globals()['Affiliation'] = Affiliation
globals()['BackupContact'] = BackupContact
globals()['UpdateCustomerPayloadCurrentAddress'] = UpdateCustomerPayloadCurrentAddress
from ghc_client.model.create_customer_payload import CreateCustomerPayload


class TestCreateCustomerPayload(unittest.TestCase):
    """CreateCustomerPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateCustomerPayload(self):
        """Test CreateCustomerPayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateCustomerPayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
