"""
    move.mil API

    The API for move.mil  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: dp3@truss.works
    Generated by: https://openapi-generator.tech
"""


import unittest

import ghc_client
from ghc_client.api.payment_service_item_api import PaymentServiceItemApi  # noqa: E501


class TestPaymentServiceItemApi(unittest.TestCase):
    """PaymentServiceItemApi unit test stubs"""

    def setUp(self):
        self.api = PaymentServiceItemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_update_payment_service_item_status(self):
        """Test case for update_payment_service_item_status

        Change the status of a payment service item for a move by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
