"""
    MilMove GHC API

    The GHC API is a RESTful API that enables the Office application for MilMove.  All endpoints are located under `/ghc/v1`.   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: milmove-developers@caci.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ghc_client
from ghc_client.model.destination_type import DestinationType
from ghc_client.model.loa_type_nullable import LOATypeNullable
from ghc_client.model.mto_agents import MTOAgents
from ghc_client.model.mto_shipment_type import MTOShipmentType
from ghc_client.model.storage_facility import StorageFacility
from ghc_client.model.update_customer_payload_current_address import UpdateCustomerPayloadCurrentAddress
from ghc_client.model.update_ppm_shipment import UpdatePPMShipment
globals()['DestinationType'] = DestinationType
globals()['LOATypeNullable'] = LOATypeNullable
globals()['MTOAgents'] = MTOAgents
globals()['MTOShipmentType'] = MTOShipmentType
globals()['StorageFacility'] = StorageFacility
globals()['UpdateCustomerPayloadCurrentAddress'] = UpdateCustomerPayloadCurrentAddress
globals()['UpdatePPMShipment'] = UpdatePPMShipment
from ghc_client.model.update_shipment import UpdateShipment


class TestUpdateShipment(unittest.TestCase):
    """UpdateShipment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateShipment(self):
        """Test UpdateShipment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateShipment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
