"""
    MilMove GHC API

    The GHC API is a RESTful API that enables the Office application for MilMove.  All endpoints are located under `/ghc/v1`.   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: milmove-developers@caci.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ghc_client
from ghc_client.model.available_office_user import AvailableOfficeUser
globals()['AvailableOfficeUser'] = AvailableOfficeUser
from ghc_client.model.available_office_users import AvailableOfficeUsers


class TestAvailableOfficeUsers(unittest.TestCase):
    """AvailableOfficeUsers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailableOfficeUsers(self):
        """Test AvailableOfficeUsers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AvailableOfficeUsers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
