"""
    move.mil API

    The API for move.mil  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: dp3@truss.works
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ghc_client
from ghc_client.model.address import Address
from ghc_client.model.destination_type import DestinationType
from ghc_client.model.loa_type import LOAType
from ghc_client.model.mto_agents import MTOAgents
from ghc_client.model.mto_service_items import MTOServiceItems
from ghc_client.model.mto_shipment_status import MTOShipmentStatus
from ghc_client.model.mto_shipment_type import MTOShipmentType
from ghc_client.model.reweigh import Reweigh
from ghc_client.model.sit_extensions import SITExtensions
from ghc_client.model.sit_status import SITStatus
from ghc_client.model.storage_facility import StorageFacility
globals()['Address'] = Address
globals()['DestinationType'] = DestinationType
globals()['LOAType'] = LOAType
globals()['MTOAgents'] = MTOAgents
globals()['MTOServiceItems'] = MTOServiceItems
globals()['MTOShipmentStatus'] = MTOShipmentStatus
globals()['MTOShipmentType'] = MTOShipmentType
globals()['Reweigh'] = Reweigh
globals()['SITExtensions'] = SITExtensions
globals()['SITStatus'] = SITStatus
globals()['StorageFacility'] = StorageFacility
from ghc_client.model.mto_shipment import MTOShipment


class TestMTOShipment(unittest.TestCase):
    """MTOShipment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMTOShipment(self):
        """Test MTOShipment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MTOShipment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
