"""
    move.mil API

    The API for move.mil  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: dp3@truss.works
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ghc_client
from ghc_client.model.payment_request_status import PaymentRequestStatus
globals()['PaymentRequestStatus'] = PaymentRequestStatus
from ghc_client.model.update_payment_request_status_payload import UpdatePaymentRequestStatusPayload


class TestUpdatePaymentRequestStatusPayload(unittest.TestCase):
    """UpdatePaymentRequestStatusPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdatePaymentRequestStatusPayload(self):
        """Test UpdatePaymentRequestStatusPayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdatePaymentRequestStatusPayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
