"""
    MilMove GHC API

    The GHC API is a RESTful API that enables the Office application for MilMove.  All endpoints are located under `/ghc/v1`.   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: dp3@truss.works
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ghc_client
from ghc_client.model.update_max_billable_weight_as_tio_payload import UpdateMaxBillableWeightAsTIOPayload


class TestUpdateMaxBillableWeightAsTIOPayload(unittest.TestCase):
    """UpdateMaxBillableWeightAsTIOPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateMaxBillableWeightAsTIOPayload(self):
        """Test UpdateMaxBillableWeightAsTIOPayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateMaxBillableWeightAsTIOPayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
