"""
    MilMove GHC API

    The GHC API is a RESTful API that enables the Office application for MilMove.  All endpoints are located under `/ghc/v1`.   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: milmove-developers@caci.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import ghc_client
from ghc_client.api.transportation_office_api import TransportationOfficeApi  # noqa: E501


class TestTransportationOfficeApi(unittest.TestCase):
    """TransportationOfficeApi unit test stubs"""

    def setUp(self):
        self.api = TransportationOfficeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_transportation_offices(self):
        """Test case for get_transportation_offices

        Returns the transportation offices matching the search query  # noqa: E501
        """
        pass

    def test_get_transportation_offices_open(self):
        """Test case for get_transportation_offices_open

        Returns the transportation offices matching the search query  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
