"""
    move.mil API

    The API for move.mil  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: dp3@truss.works
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ghc_client
from ghc_client.model.tac_valid import TacValid


class TestTacValid(unittest.TestCase):
    """TacValid unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTacValid(self):
        """Test TacValid"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TacValid()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
