"""
    MilMove Internal API

    The Internal API is a RESTful API that enables the Customer application for MilMove.  All endpoints are located under `/internal`.   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: ppp@truss.works
    Generated by: https://openapi-generator.tech
"""


import unittest

import internal_client
from internal_client.api.postal_codes_api import PostalCodesApi  # noqa: E501


class TestPostalCodesApi(unittest.TestCase):
    """PostalCodesApi unit test stubs"""

    def setUp(self):
        self.api = PostalCodesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_validate_postal_code_with_rate_data(self):
        """Test case for validate_postal_code_with_rate_data

        Validate if a zipcode is valid for origin or destination location for a move.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
