"""
    MilMove Internal API

    The Internal API is a RESTful API that enables the Customer application for MilMove.  All endpoints are located under `/internal`.   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: ppp@truss.works
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import internal_client
from internal_client.model.ppm_incentive import PPMIncentive


class TestPPMIncentive(unittest.TestCase):
    """PPMIncentive unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPPMIncentive(self):
        """Test PPMIncentive"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PPMIncentive()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
