"""
    my.move.mil

    The internal/website API for my.move.mil  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: ppp@truss.works
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import internal_client
from internal_client.model.category_expense_summary import CategoryExpenseSummary
from internal_client.model.expense_summary_payload_grand_total import ExpenseSummaryPayloadGrandTotal
globals()['CategoryExpenseSummary'] = CategoryExpenseSummary
globals()['ExpenseSummaryPayloadGrandTotal'] = ExpenseSummaryPayloadGrandTotal
from internal_client.model.expense_summary_payload import ExpenseSummaryPayload


class TestExpenseSummaryPayload(unittest.TestCase):
    """ExpenseSummaryPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExpenseSummaryPayload(self):
        """Test ExpenseSummaryPayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExpenseSummaryPayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
