"""
    my.move.mil

    The internal/website API for my.move.mil  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: ppp@truss.works
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import internal_client
from internal_client.model.method_of_receipt import MethodOfReceipt
from internal_client.model.reimbursement_status import ReimbursementStatus
globals()['MethodOfReceipt'] = MethodOfReceipt
globals()['ReimbursementStatus'] = ReimbursementStatus
from internal_client.model.reimbursement import Reimbursement


class TestReimbursement(unittest.TestCase):
    """Reimbursement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReimbursement(self):
        """Test Reimbursement"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Reimbursement()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
