"""
    my.move.mil

    The internal/website API for my.move.mil  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: ppp@truss.works
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import internal_client
from internal_client.model.address import Address
from internal_client.model.affiliation import Affiliation
from internal_client.model.service_member_rank import ServiceMemberRank
globals()['Address'] = Address
globals()['Affiliation'] = Affiliation
globals()['ServiceMemberRank'] = ServiceMemberRank
from internal_client.model.patch_service_member_payload import PatchServiceMemberPayload


class TestPatchServiceMemberPayload(unittest.TestCase):
    """PatchServiceMemberPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchServiceMemberPayload(self):
        """Test PatchServiceMemberPayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchServiceMemberPayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
