"""
    MilMove Internal API

    The Internal API is a RESTful API that enables the Customer application for MilMove.  All endpoints are located under `/internal`.   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: ppp@truss.works
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import internal_client
from internal_client.model.create_reimbursement import CreateReimbursement
from internal_client.model.document_payload import DocumentPayload
from internal_client.model.t_shirt_size import TShirtSize
globals()['CreateReimbursement'] = CreateReimbursement
globals()['DocumentPayload'] = DocumentPayload
globals()['TShirtSize'] = TShirtSize
from internal_client.model.create_personally_procured_move_payload import CreatePersonallyProcuredMovePayload


class TestCreatePersonallyProcuredMovePayload(unittest.TestCase):
    """CreatePersonallyProcuredMovePayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreatePersonallyProcuredMovePayload(self):
        """Test CreatePersonallyProcuredMovePayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreatePersonallyProcuredMovePayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
