"""
    MilMove Internal API

    The Internal API is a RESTful API that enables the Customer application for MilMove.  All endpoints are located under `/internal`.   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: ppp@truss.works
    Generated by: https://openapi-generator.tech
"""


import unittest

import internal_client
from internal_client.api.calendar_api import CalendarApi  # noqa: E501


class TestCalendarApi(unittest.TestCase):
    """CalendarApi unit test stubs"""

    def setUp(self):
        self.api = CalendarApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_show_available_move_dates(self):
        """Test case for show_available_move_dates

        Returns available dates for the move calendar  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
