"""
    my.move.mil

    The internal/website API for my.move.mil  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: ppp@truss.works
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import internal_client
from internal_client.model.address import Address
from internal_client.model.affiliation import Affiliation
from internal_client.model.transportation_office import TransportationOffice
globals()['Address'] = Address
globals()['Affiliation'] = Affiliation
globals()['TransportationOffice'] = TransportationOffice
from internal_client.model.duty_location_payload import DutyLocationPayload


class TestDutyLocationPayload(unittest.TestCase):
    """DutyLocationPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDutyLocationPayload(self):
        """Test DutyLocationPayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DutyLocationPayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
