"""
    my.move.mil

    The internal/website API for my.move.mil  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: ppp@truss.works
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import internal_client
from internal_client.model.role import Role


class TestRole(unittest.TestCase):
    """Role unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRole(self):
        """Test Role"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Role()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
