"""
    MilMove Internal API

    The Internal API is a RESTful API that enables the Customer application for MilMove.  All endpoints are located under `/internal`.   # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: ppp@truss.works
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import internal_client
from internal_client.model.document import Document
from internal_client.model.ppm_status import PPMStatus
from internal_client.model.reimbursement import Reimbursement
from internal_client.model.t_shirt_size import TShirtSize
globals()['Document'] = Document
globals()['PPMStatus'] = PPMStatus
globals()['Reimbursement'] = Reimbursement
globals()['TShirtSize'] = TShirtSize
from internal_client.model.personally_procured_move_payload import PersonallyProcuredMovePayload


class TestPersonallyProcuredMovePayload(unittest.TestCase):
    """PersonallyProcuredMovePayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPersonallyProcuredMovePayload(self):
        """Test PersonallyProcuredMovePayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PersonallyProcuredMovePayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
