#!/usr/bin/env bash

set -euo pipefail
set -x

echo "${DOCKER_PASSWORD}" | \
  docker login --username "${DOCKER_USERNAME}" --password-stdin

tag=${CODEBUILD_RESOLVED_SOURCE_VERSION:-exp}
image="${ECR_REPO}:${tag}"

docker build -t "${image}" .

aws ecr get-login-password --region "${AWS_REGION}" \
  | docker login --username AWS --password-stdin "${ECR_REPO}"

docker push "${ECR_REPO}:${tag}"

#This will return an inactive task definition if a new one has been published
#In that scenario you can specify the new revision manually in update-service
current_task_definition=$(aws ecs describe-services \
                              --cluster loadtesting \
                              --service exp-web)

task_definition_name=$(echo "${current_task_definition}" | \
                            jq  '.services[0].taskDefinition' | \
                            cut -d/ -f 2 | \
                            tr -d '"')

taskDefinitionKeys=(containerDefinitions
                    family
                    taskRoleArn
                    executionRoleArn
                    networkMode
                    volumes
                    placementConstraints
                    cpu
                    memory)

joinedKeys=$(printf ",%s" "${taskDefinitionKeys[@]}")
# remove leading comma
joinedKeys=${joinedKeys:1}

jq_filter=".taskDefinition | {${joinedKeys}}"

raw_task_definition=$(aws ecs describe-task-definition \
                          --task-definition "${task_definition_name}" | \
                        jq "${jq_filter}")

# LOCUSTFILE can be set in the build overrides of the CodeBuild config
: "${LOCUSTFILE:=/app/locustfiles/prime.py}"
# update with new settings (e.g. image)
new_task_definition=$(
  echo "${raw_task_definition}" | \
    jq ".containerDefinitions[0].image = \"${image}\"" | \
    jq ".containerDefinitions[0].entryPoint = [\"locust\"]" | \
    jq ".containerDefinitions[0].command = [\"-f\", \"${LOCUSTFILE}\", \"--host\", \"dp3\", \"--web-port\", \"4000\"]" \
                   )
new_task_definition_name=$(aws ecs register-task-definition --cli-input-json "${new_task_definition}" | \
                             jq '.taskDefinition.taskDefinitionArn' | \
                             cut -d/ -f 2 | \
                             tr -d '"')

# use force-new-deployment in case we are re-running the build and the
# image isn't changing
aws ecs update-service \
    --cluster loadtesting \
    --service exp-web \
    --task-definition "${new_task_definition_name}" \
    --desired-count 1 \
    --force-new-deployment

exit 0
