#!/usr/bin/env bash

set -euo pipefail
set -x

echo "${DOCKER_PASSWORD}" | \
  docker login --username "${DOCKER_USERNAME}" --password-stdin

docker build -t "${ECR_REPO}:exp" --build-arg locustfile="${LOCUSTFILE}" .

aws ecr get-login-password --region $AWS_REGION \
  | docker login --username AWS --password-stdin "${ECR_REPO}"

docker push "${ECR_REPO}:exp"

current_task_definition=$(aws ecs describe-services \
                              --cluster loadtesting \
                              --service exp-web | \
                            jq  '.services[0].taskDefinition' | \
                            cut -d/ -f 2 | \
                            tr -d '"')

aws ecs update-service \
    --cluster loadtesting \
    --service exp-web \
    --task-definition "${current_task_definition}" \
    --desired-count 1

exit 0
