#!/usr/bin/env bash

set -euo pipefail
set -x

echo "${DOCKER_PASSWORD}" | \
  docker login --username "${DOCKER_USERNAME}" --password-stdin

# CODEBUILD_RESOLVED_SOURCE_VERSION is the git sha
tag=${CODEBUILD_RESOLVED_SOURCE_VERSION:-exp}
image="${ECR_REPO}:${tag}"

# see https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html
docker build \
       --build-arg "GIT_COMMIT=${CODEBUILD_RESOLVED_SOURCE_VERSION}" \
       -t "${image}" .

aws ecr get-login-password --region "${AWS_REGION}" \
  | docker login --username AWS --password-stdin "${ECR_REPO}"

export ECS_TASK_IMAGE="${ECR_REPO}:${tag}"
docker push "${ECS_TASK_IMAGE}"

script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

exec "${script_dir}/ecs-deploy.py"
