#!/usr/bin/env bash

set -eu

script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
main_dir=$(cd -- "${script_dir}/.." &>/dev/null && pwd)

mymove_dir=${MYMOVE_DIR:-${main_dir}/../mymove}

cd "${main_dir}"
mkdir -p openapi_client

# openapi-generator-cli v6.1.0 is the last version that uses
# the older python geneator. In 6.2 they switched to a new generator
# that is not compatiable with our swagger definitions
#
# openapi-generator-cli v6.1.0 uses openjdk 11, which is docker aware
# so setting memory limits on the container are respected by the JVM
for client in ghc internal prime; do
  rm -rf openapi_client/${client}
  docker run -it --rm \
         --platform linux/amd64 \
         -v "${mymove_dir}:/a" \
         -v "${main_dir}:/b" \
         -m 2g \
         openapitools/openapi-generator-cli:v6.1.0 \
         generate \
         -g python \
         -i "/a/swagger/${client}.yaml" \
         -o "/b/openapi_client/${client}" \
         "--additional-properties=packageName=${client}_client"
done

pipenv install
